# Generated by Django 5.2.1 on 2025-05-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_alter_dayentry_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayentry',
            name='date',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='dayentry',
            name='day_name',
            field=models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miercoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sabado'), ('domingo', 'Domingo')], max_length=10, verbose_name='Dia'),
        ),
        migrations.AlterField(
            model_name='weekplanner',
            name='start_day',
            field=models.DateField(unique=True),
        ),
    ]
