# Generated by Django 5.2.1 on 2025-06-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_alter_dayentry_date_alter_dayentry_day_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayentry',
            name='day_name',
            field=models.CharField(choices=[('lunes', 'LLunes'), ('martes', 'Martes'), ('miercoles', 'Miercoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sabado'), ('domingo', 'Domingo')], max_length=10, verbose_name='Dia'),
        ),
    ]
