# Generated by Django 5.2.1 on 2025-06-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_alter_dayentry_day_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayentry',
            name='day_name',
            field=models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miercoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sabado'), ('domingo', 'Domingo')], max_length=10, verbose_name='Dia'),
        ),
    ]
